### ISSUE TITLE
"No results" reported by importer

### ISSUE THREAD

**Issue by bbtufty** [mylar3/mylar3#1359]
**Describe the bug**
I'm trying to import files, but for some it seems not enough metadata is parsed for the import to succeed (maybe it should use publisher as well or something?). In one case the name is parsed properly, all the files are tagged with ComicRack tags, but the import process doesn't match it at all.

**CarePackage**
[carepackage_6624039344057b6ce58f1ae2e1b843357b91df92_(python3-dev).zip](https://github.com/mylar3/mylar3/files/11597232/carepackage_6624039344057b6ce58f1ae2e1b843357b91df92_.python3-dev.zip)

**Environment (please complete the following information):**
 - OS: Synology
 - Branch / commit: nightly

**Additional information**
Add any other information about the problem here.

**Comment by bbtufty** [comment]
On further digging, it seems the reason this is happening is because newer ComicTagger versions don't save an [Issue ID: XXXXXXX] into the 'notes' part of the metadata. The issue ID would be there in the 'Web' part of the XML, but would require a little parsing:

```
cv_url = tree.find('Web').text
issue_id = cv_url.strip('/').split('/')[-1].split('-')[-1]
```

**Comment by bbtufty** [comment]
This should be fixed by PR #1360

**Comment by evilhero** [comment]
The saving of Issue ID in the notes field does still exist in CT (I just checked the source code [here](https://github.com/comictagger/comictagger/blob/develop/comictaggerlib/cli.py#L122)), so if it's not saving to your files then it's either a setting or a bug introduced in newer versions possibly.

We can parse the webpage url, but keep in mind that people use the webpage url for sources other than comicvine, so it should make sure that it's a CV url prior to trying to retrieve the issueid.

**Comment by bbtufty** [comment]
@evilhero You're totally right, it turns out it doesn't write this if 'overwrite metadata' is checked on tagging. I've edited the PR to check the webpage is a CV url

**Comment by lordwelch** [comment]
This specifically only happens with the `--overwrite` option in cli mode on version 1.5.5 more information is available here comictagger/comictagger#470
