### ISSUE TITLE
Cannot ReTag files

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#150]
**Describe the bug**
I cannot run the "Manually ReTag" option for a new series

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4276594/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Branch / commit: Version: adc9bb5ecad33428fb36b74c53c1b4e9b76f939c (python3-dev)

**Additional information**
It did change the permission properly

**Comment by evilhero** [comment]
Did you just copy the mylar3 repo into your existing repo? You have a tonne of files that are in a modified state in your mylar3 directory which means they're different than what's in the actual repo. 

From the root of the mylar3, try doing a ```git pull``` to see if it can bring things down. The idea being that you don't want anything that's different when you do a ```git status```. If everything is in order,  from the root of mylar3 again, you should be able to do a ```python3 comictagger.py --version``` and have it spit back relevant information with no errors.

**Comment by DrSeussFreak** [comment]
no, I cloned the repo into /opt/mylar3, then I copied the cache directory, mylar.db and config.ini into mylar3 (mylar2 ran in /opt/Mylar).

I ran git pull and and a ton of files were dowloaded, so I just recloned from the repo.

python3 comictagger.py --version
ComicTagger 1.3.2 [ninjas.walk.alone / SHURIKEN]
Copyright (c) 2012-2020 ComicTagger Team
Distributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

I just re-ran the option for manually retag and the same error is occurring (but in the new clone, git pull is up-to-date)

[carepackage.zip](https://github.com/mylar3/mylar3/files/4277091/carepackage.zip)

**Comment by evilhero** [comment]
ok, you need to edit your config.ini (with mylar not running):

Under the [general] section, find & delete:
```ct_settingspath = /var/lib/mylar/.ComicTagger/settings```

Then under the [metatagging] section:
add ```/var/llib/mylar/.ComicTagger``` to ct_settingspath

Save the config, restart and that should fix it.

**Comment by DrSeussFreak** [comment]
Assuming you meant `/var/lib/mylar/.ComicTagger` and not `/var/llib/mylar/.ComicTagger`, this did not resolve my problem.

**Comment by evilhero** [comment]
can you carepackage again with the ct_settingspath updated ?

**Comment by DrSeussFreak** [comment]
here you go, with 2 new files grabbed from a directory, and failed to convert to cbz
[carepackage.zip](https://github.com/mylar3/mylar3/files/4277221/carepackage.zip)

**Comment by evilhero** [comment]
Is ```settings``` a directory in here : /var/lib/mylar/.ComicTagger/ ? It can't create the settings file if a directory exists with the same name according to the error ( I think )

**Comment by DrSeussFreak** [comment]
settings does exist there already

**Comment by evilhero** [comment]
is it a directory or a file ? If it's a directory, you need to delete it.

**Comment by DrSeussFreak** [comment]
it was a directory, it has been deleted, and that did the trick!  Much obliged :)
