### ISSUE TITLE
Error when adding a comic from search

### ISSUE THREAD

**Issue by raedwa01** [mylar3/mylar3#161]
When adding a comic from a search result, the screen goes back to my manage screen and doesn't add the comic selected.

In the carepackage, this is happening at the line dated Mar 3 21:54:05.  Adding items from weekly pull list followed below.  They added, but also threw errors.

**Environment (please complete the following information):**
 - OS: docker/linux
 - Branch / commit: Mylar3/master

**Additional information**
Add any other information about the problem here.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4284846/carepackage.zip)

**Comment by evilhero** [comment]
see #162

**Comment by lboyce** [comment]
I added the comic directory when I set up my Mylar and I'm still getting this exact same issue. Can add comics from the Pull List but not a search. It just spits me back to the manage screen without adding the comic. I've double and triple-checked that I have the Comic Location Path specified.

**Comment by evilhero** [comment]
@lboyce, different issue than the OP. He's talking about adding via the search bar, you're talking about importing. Please create a seperate issue and follow the issue template.

**Comment by lboyce** [comment]
@evilhero I believe that is what I'm talking about too. His issue reads exactly like mine. I look up a series in the search, try to add the comic and the program spits me back to the manage screen without adding the book. 

I'm attempting to create a carepackage but it keeps giving me a "500 Internal Error" message. 

**Environment (please complete the following information):**

- OS: Windows
- Branch / commit: Mylar3/python3-dev

**Comment by evilhero** [comment]
@lboyce, can you paste the 500 error you're receiving ? I just pushed a fix for the carepackage, but because you're on Windows it might be something totally different than what I just patched.

**Comment by lboyce** [comment]
Yes sir.

```
Traceback (most recent call last):
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\users\lukes\applications\Mylar3\mylar\webserve.py", line 5617, in carepackage
    cp = carePackage()
  File "c:\users\lukes\applications\Mylar3\mylar\carepackage.py", line 25, in __init__
    self.environment()
  File "c:\users\lukes\applications\Mylar3\mylar\carepackage.py", line 60, in environment
    text=True)
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by evilhero** [comment]
@lboyce , Oh you're running from source I'm guessing right - not a git install correct ?

**Comment by lboyce** [comment]
Correct, I believe? I’m not particularly adept at this stuff. I run from “pip” not “pip3”

**Comment by evilhero** [comment]
ok, should be working now - just update to the latest development and you should be able to get that carepackage generated.

**Comment by lboyce** [comment]
Still getting an error when I try the carepackage after updating. 

```
Traceback (most recent call last):
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\users\lukes\applications\Mylar3\mylar\webserve.py", line 5617, in carepackage
    cp = carePackage()
  File "c:\users\lukes\applications\Mylar3\mylar\carepackage.py", line 26, in __init__
    self.cleaned_config()
  File "c:\users\lukes\applications\Mylar3\mylar\carepackage.py", line 135, in cleaned_config
    if all([tmpconfig.get(v[0], v[1]) is not None, tmpconfig.get(v[0], v[1]) != 'None']):
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'NMA'
```

**Comment by lboyce** [comment]
This is the error message I keep noticing when I try to add a comic from a search result..

`Uncaught exception: Traceback (most recent call last):
File "c:\users\lukes\applications\Mylar3\mylar\logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "C:\Users\lukes\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "c:\users\lukes\applications\Mylar3\mylar\importer.py", line 61, in addComictoDB
comlocation = os.path.dirname(imported['filelisting'][0]['comiclocation'])
TypeError: string indices must be integers`

**Comment by evilhero** [comment]
Ok, carepackage 'should' be fixed now (I keep on shooting myself in the foot with this one).

From what screen are you trying to add the search result from - the search results page after performing a search for series located at the top of the page?

**Comment by lboyce** [comment]
Ok, I got the carepackage. The update worked, but it seems to be too big to post directly here so here's a download link: https://file.io/zbfVEe

I'm trying to add the comic from the search result page, after performing a search for a title. 

<img width="1103" alt="Screen Shot 2020-03-07 at 11 29 20 AM" src="https://user-images.githubusercontent.com/80273/76148048-1bf30c80-6068-11ea-9eae-f51340fe240a.png">

**Comment by evilhero** [comment]
@lboyce update and try it now - should be good to go at this point (I'm hoping at least).

**Comment by lboyce** [comment]
Yep! Happy to report that its working great! Thanks!
