### ISSUE TITLE
Manual Recheck Files - Failing

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#548]
**Describe the bug**
I have a placed a file into the mylar created directory, and when I click recheck files, it is throwing an error about the file name.  The files name is 'Star Trek Voyager - Sevens Reckoning 01.cbr'

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5578067/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.10
 - Branch / commit: Version: f79386ea883ad34fc53e8e4c23a54209978cb5d7 (python3-dev)

**Comment by barbequesauce** [comment]
Looks like a permissions or ACL issue?

`21-Nov-2020 11:20:55 - ERROR   :: -REDACTED-.setperms.1811 : Thread-28 : [ERROR @ path: /media/comics/IDW Publishing/Star Trek Voyager - Sevens Reckoning [2020]] [Errno 1] Operation not permitted: '/media/comics/IDW Publishing/Star Trek Voyager - Sevens Reckoning [2020]/Star Trek Voyager - Sevens Reckoning 01.cbr'. Exiting...`

**Comment by DrSeussFreak** [comment]
It is not

`drwxrwxrwx   2 nobody users  4096 Nov 21 11:20 'Star Trek Voyager - Sevens Reckoning [2020]'`

```
ls -la Star\ Trek\ Voyager\ -\ Sevens\ Reckoning\ \[2020\]
total 26648
drwxrwxrwx   2 nobody users     4096 Nov 21 11:20  .
drwxrwxrwx 121 nobody users    12288 Nov 21 11:12  ..
-rwxrwxrwx   1 nobody users       79 Nov 21 11:20  cvinfo
-rwxrwxrwx   1 nobody users 27265075 Nov 18 09:49 'Star Trek Voyager - Sevens Reckoning 01.cbr'
```

It is an NFS share, with nobody:users as owner with 777 permissions.  I set this manually when I saw that error message

**Comment by barbequesauce** [comment]
The error being reported is an OS error, not Mylar... are you sure the mount is rw? Can you getfacl the directory and confirm that it's good? Not sure how else to help...

**Comment by DrSeussFreak** [comment]
this is the only series having this problem, and my entire catalog is on this mount (all with the same permissions).  

I just re-ran `chown -R nobody:users /media/comics`, with the same results.

```
root@host-01:/media/comics/IDW Publishing# getfacl /media/comics/IDW\ Publishing/Star\ Trek\ Voyager\ -\ Sevens\ Reckoning\ \[2020\]/
getfacl: Removing leading '/' from absolute path names
# file: media/comics/IDW Publishing/Star Trek Voyager - Sevens Reckoning [2020]/
# owner: nobody
# group: users
user::rwx
group::rwx
other::rwx

root@host-01:/media/comics/IDW Publishing# getfacl /media/comics/IDW\ Publishing/
getfacl: Removing leading '/' from absolute path names
# file: media/comics/IDW Publishing/
# owner: nobody
# group: users
user::rwx
group::rwx
other::rwx

root@host-01:/media/comics/IDW Publishing# getfacl /media/comics
getfacl: Removing leading '/' from absolute path names
# file: media/comics
# owner: nobody
# group: users
user::rwx
group::rwx
other::rwx

root@host-01:/media/comics/IDW Publishing# getfacl /media
getfacl: Removing leading '/' from absolute path names
# file: media
# owner: nobody
# group: users
user::rwx
group::rwx
other::rwx
```

**Comment by DrSeussFreak** [comment]
I just manually placed a file into "/media/comics/IDW Publishing/Star Wars Adventures [2020]" and hit recheck, same permissions, same ownership, it worked fine.

**Comment by DrSeussFreak** [comment]
I deleted the series from mylar, but mylar doesn't seem to recognize that I did so.

<img width="994" alt="Screen Shot 2020-11-22 at 8 48 26 PM" src="https://user-images.githubusercontent.com/175500/99925544-2b081080-2d04-11eb-935c-22621a0adad9.png">
<img width="1334" alt="Screen Shot 2020-11-22 at 8 48 51 PM" src="https://user-images.githubusercontent.com/175500/99925546-2ba0a700-2d04-11eb-9d1b-28f835b6d32e.png">

**Comment by evilhero** [comment]
Turn off enforce permissions within Mylar. It can have problems enforcing permissions on non-local mounts (you can mount NFS with a specific flag which would allow for remote ownership of I recall). 

The error being thrown is due to the mylar user trying to chown:chmod the file and not having sufficient rights due to not having sufficient permissions to the mount point (which was possibly mounted without the specified flag/perms required to allow it).

As far as the weekly pull, just try to Recreate the Pullist and it should straighten it out. It will not remove issues that were part of a deleted series  from your history however.

**Comment by DrSeussFreak** [comment]
I've disabled the setting, but the issue still shows in that manner after recreating the pull-list for that week

**Comment by evilhero** [comment]
Are you refreshing the page or just using the back button? You might have some weird caching thing happening and it's not showing properly.

As long as the series is not on your watchlist any longer, and you're viewing the given week that the mis-shown status is being displayed when doing the recreate pull - I mean, that's all there is to it ;)

If it's not flying thru, maybe restart Myalr and try doing a recreate pull again from the specific week.

**Comment by DrSeussFreak** [comment]
I was refreshing, and then I went into incognito mode, no luck.  I have restarted as well, no difference.

**Comment by evilhero** [comment]
There's something amiss tho with the permissions still. I mean there are several series in your log that seem to be having permissions issues as well (and that's just from the mylar.log file, not any of the other log files):
```
G.I. Joe [2019]
G.I. Joe A Real American Hero [2010]
Dark Horse Comics/The Orville [2020]
Star Wars Adventures [2020]
Star Wars Bounty Hunters [2020]
Star Trek Voyager - Sevens Reckoning [2020]
```
You also have some security warnings in regards to your certificate having the wrong version number: ```Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))```

Unfortunately the logs are all in WARNING level, which, I mean you know I'm going to say this- is that it's pretty useless when trying to figure out what's happening. Maybe if it's still an issue, you can do a new carepackage with debug enabled for abit prior to generating the carepackage.

**Comment by DrSeussFreak** [comment]
I fixed the SSL errors, they were related to me switching from self-signed SSL Certs to a reverse proxy, and some internal settings were overlooked.

I reproduced all the steps with debug mode enabled, hopefully this carepackage helps.

[carepackage.zip](https://github.com/mylar3/mylar3/files/5584316/carepackage.zip)

**Comment by evilhero** [comment]
So ummm, ok that log is a mess of stuff happening.

From what I can follow:
- you did a one-off download, it found it and snatched it and started downloading.
- while it was downloading, you added the series to your watchlist.
- the file finished downloading before the series was completely populated so it threw it as a one-off but failed as the series was updating as it was trying to post-process resulting in traceback error. 
- your series completed updating, but because it doesn't see the issue as downloaded as the post-processing failed so it couldn't mark it as Downloaded, it tries to download it again.
- it fails in attempting to download it again, marks it as Failed. Tries again. Tries to send to your SAB, fails as it can't send to your SAB instance and marks the download as failed.
- then it eventually downloads and post-processes but the one-off is considered a one-off in a Snatched status and doesn't line up with the series being downloaded so it stays in a Snatched status, while your series shows it as Downloaded.

Did I get close to what kind of workflow you did ?

**Comment by DrSeussFreak** [comment]
Yes, sorry about that, I already had the file downloaded, and in the torrent blackhole directory, but when I re-added the series (which I can only do by searching for it manually, since in the pull list it shows as needing to be retried, without an option to re-add).

It auto-downloaded a file, 3 times, and it was in the cache directory, but it will not post process either the files it downloads, the one I put in the blackhole, nor the file I put into the directory itself.

**Comment by evilhero** [comment]
Yeah at that point it assumes you're doing a one-off and the re-add option isn't available as it's more a space-kinda thing than anything really. And it thinks that because you already opted for the one-off that's the link that you're going to be using from that point onwards.

It won't post-process it probably because of the failed aspect.

You'll probably have to start from scratch on all of this. So try this to get back to ground zero and then we can retry:
- delete the series from your watchlist.
- shut down Mylar.
- go into sqlite3 via the command line (ie. cd to wherever your mylar.db file and type in ```sqlite3 mylar.db```)
- then: 
```delete from oneoffhistory where comicid=132112```
```delete from snatched where comicid=132112```
```delete from weekly where comicid=132112```
- exit the sqlite3 by typing in ```.exit``` or ```exit()``` (I always forget)
- start up Mylar.
- add in the series first. Wait for it to finish loading. Note that because the issue is in the current week's pull it should start searching for it during the add so you might not have to do a manual search.
- see if that works ?

**Comment by DrSeussFreak** [comment]
No luck
[Uploading carepackage.zip…]()

**Comment by evilhero** [comment]
Your git commit history says you're 5 weeks behind, but your git status shows that almost every file in the repo has been modified different than what the current repo is at (or I guess what your forkedl git repo is done against).

Either way, I think it's pretty important that you try to get on the same base as us in order to help - as I have no idea what changes you've done to your fork, as I'm not privy to that. But if you can get your repo up to the same point as ours, then at least we'll be starting from the same point.

**Comment by DrSeussFreak** [comment]
I am at a loss on what happened to my binaries, as I have made no changes.  When I try to update I get the following

![Screen Shot 2020-11-23 at 12 51 33 PM](https://user-images.githubusercontent.com/175500/100002793-a9a79100-2d8a-11eb-9ef3-1c282d598796.png)
![Screen Shot 2020-11-23 at 12 51 43 PM](https://user-images.githubusercontent.com/175500/100002794-a9a79100-2d8a-11eb-84bd-2692e9633162.png)

yet

```
/opt/mylar3# git pull
Already up to date.
```

**Comment by DrSeussFreak** [comment]
I just recloned the repo, I am not running

Version: v0.4.9.1 (master)

**Comment by evilhero** [comment]
so you're on master, but you're config.ini is set to poll against python3-dev. Either change the config.ini git_branch value to master, or do a ```git checkout python3-dev``` so that you're on the python3-dev branch.

**Comment by DrSeussFreak** [comment]
done, I ran `git checkout python3-dev`.

**Comment by evilhero** [comment]
It's still showing as being in your one-off list. Can you repeat the process I mentioned a few above - and once you start Mylar up again after doing it, do not search for it from the pull-list via the One-Off option.

**Comment by DrSeussFreak** [comment]
ok, sounds good, I was just about to post the carepackage, nothing changed on my end.

**Comment by evilhero** [comment]
When #552 gets merged into python3-dev, it should fix your problems with the pull-list not properly displaying the correct status as well as the post-processing of one-offs. You'll probably have to recreate the particular week's pull tho for it to show properly since Mylar doesn't keep monitor previous weeks for changes after the fact.

**Comment by DrSeussFreak** [comment]
Which repo would you suggest I work off of?  Master of python3-dev?

**Comment by evilhero** [comment]
Python3-dev tends to as stable as the main branch with the benefit of receiving fixes quicker. As opposed to being stable, but not receiving updates as quickly (we try for every week, but obviously sometimes life happens and things get pushed back as per the last merge)

**Comment by DrSeussFreak** [comment]
ahh, ok, so I used to use the dev branch, but it seems master / dev have swapped, and master is now the regularly updated branch?

**Comment by DrSeussFreak** [comment]
I am confirming this as fixed with the latest patch! As always, thanks!

**Comment by evilhero** [comment]
Nono, python3-dev is still the dev branch and gets more regular updates, as well as any fix will go into that branch first always. 

We're just trying to keep the main branch up to date with consistent merges.

**Comment by DrSeussFreak** [comment]
yea, I re-read and understood, I am having one of those days where I need to read something 4 times before I understand
